<script>
  export default {
    props: {
      circleindex: {
        type: Number,
        default: 1
      },
      activeindex: {
        type: Number,
        default: 1
      },
      circlecolor: {
        type: String,
        default: 'black'
      }
    },
    /*     watch: {
      activeindex(newIndex, oldIndex) {
        if (newIndex === this.circleindex) {
          this.scrollToElement(newIndex)
        }
      }
    }, */
    methods: {
      /*       scrollToElement(scrollIndex) {
        this.$refs['4'].scrollIntoView({ behavior: 'smooth' })
      },
      scrollToHiddenElement() {
        this.$refs['hiddenElement'].scrollIntoView({ behavior: 'smooth' })
      } */
    },
    computed: {
      ddd() {
        return this.$refs
      },
      circleStyles() {
        return {
          'background-color': this.circlecolor
        }
      },
      intervalActive() {
        /* return this.activeid === this.circleid */
        return this.activeindex === this.circleindex
      }
    }
  }
</script>

<template>
  <!--   <span :class="p ? 'bc' : 'cc'" /> -->

  <span
    :style="circleStyles"
    :class="intervalActive ? 'scale-down-center' : ''"
  />
</template>

<style scoped>
  span {
    display: inline-block;
    width: 1.5rem;
    height: 1.5rem;
    margin: 5px;
    border-radius: 50%;
    opacity: 0.1;
  }
  .scale-down-center {
    opacity: 1;
    -webkit-animation: scale-down-center 1s ease-in-out infinite alternate both;
    animation: scale-down-center 1s ease-in-out infinite alternate both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2022-5-6 22:13:35
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation scale-down-center
 * ----------------------------------------
 */
  @-webkit-keyframes scale-down-center {
    0% {
      -webkit-transform: scale(1.2);
      transform: scale(1.2);
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
  }
  @keyframes scale-down-center {
    0% {
      -webkit-transform: scale(1.2);
      transform: scale(1.2);
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
  }
</style>
